# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import helloworld_pb2 as helloworld__pb2


class GreeterStub(object):
    """python -m grpc_tools.protoc -I protos --python_out=. --grpc_python_out=. protos/helloworld.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/helloworld.Greeter/Login',
                request_serializer=helloworld__pb2.LoginRequest.SerializeToString,
                response_deserializer=helloworld__pb2.LoginReply.FromString,
                )
        self.IP = channel.unary_unary(
                '/helloworld.Greeter/IP',
                request_serializer=helloworld__pb2.IPRequest.SerializeToString,
                response_deserializer=helloworld__pb2.IPReply.FromString,
                )
        self.Command = channel.unary_unary(
                '/helloworld.Greeter/Command',
                request_serializer=helloworld__pb2.CommandRequest.SerializeToString,
                response_deserializer=helloworld__pb2.CommandReply.FromString,
                )
        self.Lobby = channel.unary_unary(
                '/helloworld.Greeter/Lobby',
                request_serializer=helloworld__pb2.LobbyRequest.SerializeToString,
                response_deserializer=helloworld__pb2.LobbyReply.FromString,
                )
        self.Logout = channel.unary_unary(
                '/helloworld.Greeter/Logout',
                request_serializer=helloworld__pb2.LogoutRequest.SerializeToString,
                response_deserializer=helloworld__pb2.LogoutReply.FromString,
                )


class GreeterServicer(object):
    """python -m grpc_tools.protoc -I protos --python_out=. --grpc_python_out=. protos/helloworld.proto

    """

    def Login(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IP(self, request, context):
        """Sends another greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lobby(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=helloworld__pb2.LoginRequest.FromString,
                    response_serializer=helloworld__pb2.LoginReply.SerializeToString,
            ),
            'IP': grpc.unary_unary_rpc_method_handler(
                    servicer.IP,
                    request_deserializer=helloworld__pb2.IPRequest.FromString,
                    response_serializer=helloworld__pb2.IPReply.SerializeToString,
            ),
            'Command': grpc.unary_unary_rpc_method_handler(
                    servicer.Command,
                    request_deserializer=helloworld__pb2.CommandRequest.FromString,
                    response_serializer=helloworld__pb2.CommandReply.SerializeToString,
            ),
            'Lobby': grpc.unary_unary_rpc_method_handler(
                    servicer.Lobby,
                    request_deserializer=helloworld__pb2.LobbyRequest.FromString,
                    response_serializer=helloworld__pb2.LobbyReply.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=helloworld__pb2.LogoutRequest.FromString,
                    response_serializer=helloworld__pb2.LogoutReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """python -m grpc_tools.protoc -I protos --python_out=. --grpc_python_out=. protos/helloworld.proto

    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/Login',
            helloworld__pb2.LoginRequest.SerializeToString,
            helloworld__pb2.LoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/IP',
            helloworld__pb2.IPRequest.SerializeToString,
            helloworld__pb2.IPReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/Command',
            helloworld__pb2.CommandRequest.SerializeToString,
            helloworld__pb2.CommandReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Lobby(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/Lobby',
            helloworld__pb2.LobbyRequest.SerializeToString,
            helloworld__pb2.LobbyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/Logout',
            helloworld__pb2.LogoutRequest.SerializeToString,
            helloworld__pb2.LogoutReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
